FROM node:16

WORKDIR /usr/src/app

RUN useradd -m appuser && \
    chown appuser:appuser /usr/src/app && \
    npm install -g serve && \
    npm cache clean --force && \
    rm -rf /var/lib/apt/lists/*

COPY --chown=appuser:appuser . .

USER appuser

ENV REACT_APP_BACKEND_URL="http://localhost:8080"

RUN npm install && \
    npm run build && \
    npm cache clean --force

EXPOSE 5000

CMD ["serve", "-s", "-l", "5000", "build"]
