FROM node:16-alpine

WORKDIR /usr/src/app

RUN adduser -D appuser && \
    chown appuser:appuser /usr/src/app && \
    npm install -g serve

COPY --chown=appuser:appuser . .

USER appuser

ENV REACT_APP_BACKEND_URL="http://localhost:8080"

RUN npm install && \
    npm run build && \
    npm cache clean --force

EXPOSE 5000

CMD ["serve", "-s", "-l", "5000", "build"]
