FROM golang:1.16-alpine AS build

WORKDIR /usr/src/backend

COPY . .

ENV CGO_ENABLED=0

RUN go build -o server && \
    go test ./...

FROM alpine:latest

WORKDIR /usr/src/backend

RUN adduser -D appuser

COPY --from=build /usr/src/backend/server .

RUN chown -R appuser:appuser /usr/src/backend

USER appuser

ENV PORT=8080 REQUEST_ORIGIN=http://localhost:8000

EXPOSE 8080

CMD ["./server"]
